basePath: java/io/src/main/java
basePackage: otterop.io
targetType: library
python:
  outPath: python/io/otterop/io/
ts:
  outPath: ts/io/otterop/io/
c:
  outPath: c/otterop/io/
csharp:
  outPath: dotnet/Io/Otterop/Io/
go:
  outPath: go/io/
