#ifndef __otterop_datastructure_TestStringBuffer
#define __otterop_datastructure_TestStringBuffer
#include <otterop/lang/string.h>
#include <otterop/test/test_base.h>

typedef struct otterop_lang_String_s otterop_lang_String_t;
typedef struct otterop_test_TestBase_s otterop_test_TestBase_t;

typedef struct otterop_datastructure_TestStringBuffer_s otterop_datastructure_TestStringBuffer_t;




void otterop_datastructure_TestStringBuffer_empty(otterop_datastructure_TestStringBuffer_t *this);


void otterop_datastructure_TestStringBuffer_add_more_strings(otterop_datastructure_TestStringBuffer_t *this);


void otterop_datastructure_TestStringBuffer_assert_true(otterop_datastructure_TestStringBuffer_t *this, int arg0, otterop_lang_String_t *arg1);

otterop_datastructure_TestStringBuffer_t* otterop_datastructure_TestStringBuffer_new();
#endif
