OTTEROP_IO_CONSOLE_OBJS:=otterop/io/console.o $(OTTEROP_LANG_STRING_OBJS)

OTTEROP_IO_LDFLAGS=
OTTEROP_IO_LIBRARIES=
OTTEROP_IO_INCLUDES=
OTTEROP_IO_DEPENDENCIES=

otterop/io/console.o: $(OTTEROP_LANG_STRING_OBJS)
