#ifndef __otterop_datastructure_TestInternal
#define __otterop_datastructure_TestInternal

typedef struct otterop_datastructure_TestInternal_s otterop_datastructure_TestInternal_t;




otterop_datastructure_TestInternal_t* otterop_datastructure_TestInternal_new();
#endif
